FROM python:3.12

RUN pip install Flask gunicorn firebase_admin pycryptodome==3.10.1 pyrebase4

COPY src/ /app
WORKDIR /app

ENV PORT 8080

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
